services:
  - type: web
    name: murzing-backend
    env: python
    branch: main
    buildCommand: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      source venv/bin/activate
      python app.py
    cacheDirectories:
      - .cache
      - venv